export enum StaffAlertType {
  LOW_STOCK = 'LOW_STOCK',
  REPAIR_READY = 'REPAIR_READY',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  OVERDUE_REPAIR = 'OVERDUE_REPAIR',
  LARGE_DEBT = 'LARGE_DEBT',
}
