export enum AuditAction {
  LOGIN = 'LOGIN',
  REPAIR_CREATE = 'REPAIR_CREATE',
  REPAIR_UPDATE = 'REPAIR_UPDATE',
  REPAIR_STATUS_CHANGE = 'REPAIR_STATUS_CHANGE',
  PAYMENT = 'PAYMENT',
  SALE_CREATE = 'SALE_CREATE',
  SALE_CANCEL = 'SALE_CANCEL',
  INVENTORY_CHANGE = 'INVENTORY_CHANGE',
  EMPLOYEE_CHANGE = 'EMPLOYEE_CHANGE',
  SETTINGS_CHANGE = 'SETTINGS_CHANGE',
}
